GET http://127.0.0.1:8000/ttsapi/getVoices
Content-Type: application/json


###

GET http://127.0.0.1:8000/ttsapi/testGet
Content-Type: application/json

{ "email": "adam@mail.com", "password": "Pass1234!" }

###
